"""The compliance catalog model and loader (BL-031, ADR-0021).

A pydantic-validated projection of the prose compliance map
(``docs/governance/compliance-map.md``) and the STPA security constraints
(``docs/stpa/07-security-constraints.md``) into data CI can check bidirectionally:
each control names the SEC constraint it realises, the invariants it upholds, the
source modules that enforce it (which must carry the matching ``SEC-N``
back-citation), the tests that prove it, and the regulatory articles it maps to.

This model is the single source of truth for the published JSON Schema
(``docs/schema/compliance-controls.schema.json``, regenerated by ``make schema``),
mirroring the SKILL.md frontmatter pattern (ADR-0014): pydantic at the
external-input boundary, one model behind both the parse step and the schema.
``praxis.governance.validate`` runs the cross-reference rules over a loaded catalog.
"""

from __future__ import annotations

from pathlib import Path
from typing import Literal

from pydantic import BaseModel, ConfigDict, Field

# A control is fully wired, partly wired with a tracked residual, or specified but
# not yet built. ``partial``/``planned`` MUST carry a ``tracking`` BL id; the
# validator enforces that, so the honesty annotations stay machine-checked.
ControlStatus = Literal["implemented", "partial", "planned"]


class RegulatoryRef(BaseModel):
    """One regulatory article a control maps to (the original-language convention)."""

    model_config = ConfigDict(extra="forbid", str_strip_whitespace=True)

    # ``framework`` must be a key in ``ComplianceCatalog.frameworks`` (validator R8).
    framework: str = Field(min_length=1)
    article: str = Field(min_length=1)  # e.g. "Art. 9", "Annex I (1)", "A.8.15"
    note: str = ""


class ComplianceControl(BaseModel):
    """One control: a SEC constraint (or a governance control) and its traceability."""

    model_config = ConfigDict(extra="forbid", str_strip_whitespace=True)

    title: str = Field(min_length=1)
    statement: str = Field(min_length=1)
    # The nine invariants (CLAUDE.md) this control upholds; each must be in 1..9.
    invariants: list[int] = Field(default_factory=list)
    # Repo-relative source paths that enforce the control. A SEC control's
    # ``src/praxis/**.py`` modules must contain the matching ``SEC-N`` token.
    modules: list[str] = Field(default_factory=list)
    # ``path::test_function`` ids that prove the control; each must exist.
    proving_tests: list[str] = Field(default_factory=list)
    regulatory: list[RegulatoryRef] = Field(min_length=1)
    status: ControlStatus = "implemented"
    tracking: str | None = None  # a BL-NNN id when status is partial/planned


class ComplianceCatalog(BaseModel):
    """The catalog: in-scope frameworks plus the controls, keyed by id (SEC-N/CTL-NNN)."""

    model_config = ConfigDict(extra="forbid", str_strip_whitespace=True, title="ComplianceCatalog")

    version: str = Field(min_length=1)
    # framework id (the prefix used in citations, e.g. "NIS2") -> full legal name.
    frameworks: dict[str, str] = Field(min_length=1)
    # control id ("SEC-1".."SEC-10", "CTL-001"...) -> control.
    controls: dict[str, ComplianceControl] = Field(min_length=1)


def load_catalog(path: Path) -> ComplianceCatalog:
    """Parse and validate the catalog JSON through the model (the boundary, ADR-0014).

    Raises ``pydantic.ValidationError`` on a structurally invalid document; the
    cross-reference rules (module existence, back-citation, framework coverage) live
    in ``praxis.governance.validate``.
    """
    return ComplianceCatalog.model_validate_json(path.read_text(encoding="utf-8"))
